### PR TITLE
fix OPENJDK_TAG in java version output

### LINKED ISSUE #27: fix OPENJDK_TAG in java version output
Java version output of openJ9 builds doesn't contain proper OPENJDK_TAG.

> openjdk version "1.8.0-internal"
> OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2018_01_09_13_02-b00)
> Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20180109_42 (JIT enabled, AOT enabled)
> OpenJ9   - b116fb3
> OMR      - 7a770d6
> OpenJDK  - 00e69f9 based on )

Proper output

> openjdk version "1.8.0-internal"
> OpenJDK Runtime Environment (build 1.8.0-internal-bhamaram_2018_01_10_00_29-b00)
> Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20180110_000000 (JIT enabled, AOT enabled)
> OpenJ9   - b116fb3
> OMR      - 7a770d6
> OpenJDK  - 00e69f9 based on jdk8u152-b16)

### PR DESCRIPTION
**Pull request by mbvreddy**
Signed-off-by: Bhaktavatsal Reddy <bhamaram@in.ibm.com>

Fixes #27 

Java version output of openJ9 builds doesn't contain proper OPENJDK_TAG.

> openjdk version "1.8.0-internal"
> OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2018_01_09_13_02-b00)
> Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20180109_42 (JIT enabled, AOT enabled)
> OpenJ9   - b116fb3
> OMR      - 7a770d6
> OpenJDK  - 00e69f9 based on )

Output with this fix

> openjdk version "1.8.0-internal"
> OpenJDK Runtime Environment (build 1.8.0-internal-bhamaram_2018_01_10_00_29-b00)
> Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20180110_000000 (JIT enabled, AOT enabled)
> OpenJ9   - b116fb3
> OMR      - 7a770d6
> OpenJDK  - 00e69f9 based on jdk8u152-b16)

### CODE REVIEW

File: jdk/make/closed/autoconf/generated-configure.sh [hunk 1]
```diff
@@ -8253,7 +8253,7 @@ $as_echo "$DEBUG_LEVEL" >&6; }
   elif test "x$OPENJ9_CPU" = xppc-64; then
     OPENJ9_PLATFORM_CODE=ap64
   else
-    as_fn_error $? "Unsupported OpenJ9 cpu ${OPENJ9_CPU}, contact support team!" "$LINENO" 5
```
Comment (mbvreddy) [inline jdk/make/closed/autoconf/generated-configure.sh]: This change was made in custom-hook.m4 in previous commit. However, generated-configure.sh is not generated with that change. When I run autogen.sh now to generate generated-configure.sh files, it got updated.

**Comment by mbvreddy** [comment]
Following is sequence of build

1. clone using command "git clone --depth=1 -b openj9 https://github.com/ibmruntimes/openj9-openjdk-jdk8.git /home/jenkins/workspace/openjdk8_openj9_build_x86-64_linux/openjdk"
2. fetch tags using command "git fetch -q --tags --depth=1". This happens in getOpenJDKUpdateAndBuildVersion() function of makejdk.sh before actual build happens.
3. Build JDK using "make images"

OPENJDK_TAG is computed in Step 3 (while building JDK i.e., "make images"). Technically tags has been fetched properly in clone by that time.

> bhamaram@jcllnx01:~/adoptopenjdk/test-openjdk$ git show-ref --tags -d
> 2414ebd2ae20719019f3d354aa742643c10be7d0 refs/tags/jdk8u152-b16
> 84153c75da79342522533371b19330181ab4ff4f refs/tags/jdk8u152-b16^{}

OPENJDK_TAG is computed by fetching tags on latest revision of "openj9" branch for which there are no tags. This fix aims at using fallback mechanism of fetching tag in same way as in step 2 i.e., in getOpenJDKUpdateAndBuildVersion() function

**Comment by mbvreddy** [comment]
OPENJDK_TAG has been fetched using commands

> OPENJDK_SHA=`git -C $SRC_ROOT rev-parse --short HEAD`
> OPENJDK_TAG=`git -C $SRC_ROOT describe --abbrev=0 --tags`

As seen above, TAG has been fetched from the latest revision (which doesn't have any tags). Output of those commands on local machine after  makejdk-any-platform.sh is complete. Any timing windows that exist in fetching tags while building should have sorted by now.

```
bhamaram@jcllnx01:~/adoptopenjdk/openjdk$ git -C /home/bhamaram/adoptopenjdk/openjdk rev-parse --short HEAD
00e69f9
bhamaram@jcllnx01:~/adoptopenjdk/openjdk$ git -C /home/bhamaram/adoptopenjdk/openjdk describe --abbrev=0 --tags
fatal: No tags can describe '00e69f903e2ca179e999c27b3cfbe4cb536d8e72'.
Try --always, or create some tags.
```

This proves that issue is not due to timing window in openjdk-build scripts.

**Comment by jdekonin** [comment]
Two questions:
- why does it work fine if its a full clone?
- why is the output from the execution of getOpenJDKUpdateAndBuildVersion always show up after the sdk is generated?

**Comment by mbvreddy** [comment]
getOpenJDKUpdateAndBuildVersion() use getFirstTagFromOpenJDKGitRepo() to get OpenJDK tag. Output of this is seen before JDK build start.
```
echo "${git}Pulling latest tags and getting the latest update version using git fetch -q --tags ${SHALLOW_CLONE_OPTION}"
git fetch -q --tags "${SHALLOW_CLONE_OPTION}"
OPENJDK_REPO_TAG=$(getFirstTagFromOpenJDKGitRepo)
if [[ "${OPENJDK_REPO_TAG}" == "" ]] ; then
 echo "${error}Unable to detect git tag"
 exit 1
else
 echo "OpenJDK repo tag is $OPENJDK_REPO_TAG"
fi
```
At the end, after completing JDK build, in createOpenJDKTarArchive() function, OpenJDK tag is determined once again using  getFirstTagFromOpenJDKGitRepo()
```
createOpenJDKTarArchive()
{
  echo "Archiving the build OpenJDK image..."

  OPENJDK_REPO_TAG=$(getFirstTagFromOpenJDKGitRepo)
  echo "OpenJDK repo tag is ${OPENJDK_REPO_TAG}"
  .
  .
}
```

I realized that full clone (removing depth=1) works as it downloads everything. Existing commands to fetch tags from latest revision worked. However, it consumed more disk space (full clone is 1.1GB and shallow-clone is 552MB) and thereby took more time to clone.

**Comment by mbvreddy** [comment]
Copyright check failed for common/autoconf/generated-configure.sh.

Technically, this fix doesn't have any changes to that file. However, when I run autogen tool after changing custom-hook.m4, this file got updated with timestamp automatically and it came along with commit.

I will see how can I remove this from this commit.
