### PR TITLE
fix ReleasePrimitiveArrayCritical() calls properly in NativeCrypto.c

### LINKED ISSUE #153: [OpenJ9#3413] Crash in GC due to incorrect arguments to ReleasePrimitiveArrayCritical() in NativeCrypto.c
This issue is opened to fix the Crash issue reported in https://github.com/eclipse/openj9/issues/3413

```
----------- Stack Backtrace -----------
(0x00007F91B731FB20 [libj9gc29.so+0x65b20])
Java_jdk_crypto_jniprovider_NativeCrypto_DigestUpdate+0x5c (0x00007F910961D73C [libjncrypto.so+0x173c])
(0x00007F91216A2B6C [<unknown>+0x0])
---------------------------------------
```

Third argument to ReleasePrimitiveArrayCritical() should be the return value of GetPrimitiveArrayCritical()

### PR DESCRIPTION
**Pull request by mbvreddy**
fixes #153 
fixes eclipse/openj9#3413

This fix handles GetPrimitiveArrayCritical/ReleasePrimitiveArrayCritical calls as per specification.

Signed-off-by: Bhaktavatsal Reddy <bhamaram@in.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
@gacholio @dmitripivkine can you please review

File: closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c [hunk 1]
```diff
@@ -162,19 +165,31 @@ JNIEXPORT jint JNICALL Java_jdk_crypto_jniprovider_NativeCrypto_DigestComputeAnd
...
+        messageNative = messageNative + messageOffset;
+
+        if (1 != EVP_DigestUpdate(context->ctx, messageNative, messageLen))
+            handleErrors();
+
+        (*env)->ReleasePrimitiveArrayCritical(env, message, messageNative, 0);
     }
 
     digestNative = (*env)->GetPrimitiveArrayCritical(env, digest , &isCopy);
+
```
Comment (gacholio) [inline closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c]: Above line will not compile as isCopy is removed.

File: closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c [hunk 2]
```diff
@@ -162,19 +165,31 @@ JNIEXPORT jint JNICALL Java_jdk_crypto_jniprovider_NativeCrypto_DigestComputeAnd
...
-       messageNative = (*env)->GetPrimitiveArrayCritical(env, message, &isCopy);
-       messageNative = messageNative + messageOffset;
-       if (1 != EVP_DigestUpdate(context->ctx, messageNative, messageLen)) handleErrors();
-           (*env)->ReleasePrimitiveArrayCritical(env, message, NULL, 0);
+        messageNative = (*env)->GetPrimitiveArrayCritical(env, message, &isCopy);
+
+        if (messageNative == NULL)
+            return -1;
+
+        messageNative = messageNative + messageOffset;
```
Comment (dmitripivkine) [inline closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c]: This line modify an original messageNative so it can not be used in ReleasePrimitiveArrayCritical()

Comment (mbvreddy) [reply closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c]: Oh.. Yes! I will address this.

File: closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c (hunk 1 above)
Comment (mbvreddy) [reply closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c]: isCopy is not removed for this method. But, it has to be removed as we do not rely on this flag.

**Comment by mbvreddy** [comment]
No new failures with this change.

TEST STATS: name=jdk_security1  run=169  pass=169  fail=0

TEST STATS: name=jdk_security2  run=171  pass=169  fail=2
	FAILED: com/sun/crypto/provider/Cipher/AES/TestAESCiphers/TestAESWithProviderChange.java
	FAILED: com/sun/crypto/provider/Cipher/AES/TestAESCiphers/TestAESWithRemoveAddProvider.java

TEST STATS: name=jdk_security3  run=525  pass=519  fail=6
	FAILED: sun/security/pkcs11/ec/TestECDH.java
	FAILED: sun/security/pkcs11/ec/TestECDSA.java
	FAILED: sun/security/pkcs11/ec/TestECGenSpec.java
	FAILED: sun/security/pkcs11/Secmod/AddTrustedCert.java
	FAILED: sun/security/pkcs11/Signature/TestDSAKeyLength.java
	FAILED: sun/security/pkcs11/tls/TestKeyMaterial.java

TEST STATS: name=jdk_security4  run=132  pass=132  fail=0

TEST STATS: name=jdk_security  run=997  pass=989  fail=8
	FAILED: com/sun/crypto/provider/Cipher/AES/TestAESCiphers/TestAESWithProviderChange.java
	FAILED: com/sun/crypto/provider/Cipher/AES/TestAESCiphers/TestAESWithRemoveAddProvider.java
	FAILED: sun/security/pkcs11/ec/TestECDH.java
	FAILED: sun/security/pkcs11/ec/TestECDSA.java
	FAILED: sun/security/pkcs11/ec/TestECGenSpec.java
	FAILED: sun/security/pkcs11/Secmod/AddTrustedCert.java
	FAILED: sun/security/pkcs11/Signature/TestDSAKeyLength.java
	FAILED: sun/security/pkcs11/tls/TestKeyMaterial.java

**Comment by mbvreddy** [comment]
@gacholio @dmitripivkine can you please review once again? I've changed after you last review.

File: closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c [hunk 3]
```diff
@@ -255,16 +260,16 @@ JNIEXPORT void JNICALL Java_jdk_crypto_jniprovider_NativeCrypto_CBCInit
             break;
     }
 
-    ivNative  = (unsigned char*)((*env)->GetByteArrayElements(env, iv,  &isCopy));
-    keyNative = (unsigned char*)((*env)->GetByteArrayElements(env, key, &isCopy));
+    ivNative = (unsigned char*)((*env)->GetByteArrayElements(env, iv, 0));
+    keyNative = (unsigned char*)((*env)->GetByteArrayElements(env, key, 0));
```
Comment (gacholio) [inline closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c]: These calls should also be error checked.

File: closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c [hunk 4]
```diff
@@ -420,22 +470,51 @@ JNIEXPORT jint JNICALL Java_jdk_crypto_jniprovider_NativeCrypto_GCMDecrypt
...
-    unsigned char* ivNative     = (unsigned char*)((*env)->GetPrimitiveArrayCritical(env, iv,    &isCopy));
-    unsigned char* outputNative = (unsigned char*)((*env)->GetPrimitiveArrayCritical(env, output,&isCopy));
-
+    unsigned char* keyNative;
+    unsigned char* ivNative;
+    unsigned char* outputNative;
     EVP_CIPHER_CTX* ctx = NULL;
 
+    keyNative = (unsigned char*)((*env)->GetPrimitiveArrayCritical(env, key, 0));
+    if (keyNative == NULL && keyLen > 0)
```
Comment (gacholio) [inline closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c]: Why the length checks here?

File: closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c (hunk 3 above)
Comment (mbvreddy) [reply closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c]: Done.. added null checks.

File: closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c (hunk 4 above)
Comment (mbvreddy) [reply closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c]: I have checked for length to ensure that return value is not NULL for valid reasons (like if source array is NULL).

Comment (mbvreddy) [reply closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c]: I've removed the length checks.

Comment (gacholio) [reply closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c]: I believe if the source array is NULL, the JNI call will crash.

**Comment by gacholio** [comment]
Look reasonable, though I agree the error handling could be more consistent. This fixes the problems reported in the issue.

File: closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c (hunk 4 above)
Comment (mbvreddy) [reply closed/adds/jdk/src/share/native/jdk/crypto/jniprovider/NativeCrypto.c]: Right.

**Comment by DanHeidinga** [comment]
Jenkins test all xlinux jdk8

**Comment by dmitripivkine** [comment]
please squash all three commits to one

**Comment by DanHeidinga** [comment]
@mbvreddy Can you squash the commits in this PR so we can get it merged?

**Comment by mbvreddy** [comment]
@DanHeidinga - done. I've squashed commits.

**Comment by DanHeidinga** [comment]
Jenkins test sanity xlinux jdk8
